### ISSUE TITLE
read ground truth depth map

### ISSUE THREAD

**Issue by lkyf** [ETH3D/dataset-pipeline#1]
When I read the depth map in *_depth.7z, I found the depth values at most pixels are inf.
Used code:
`float float_inf = std::numeric_limits<float>::infinity();

std::ifstream gt_depth_file(input_depth_path, std::ios::in | std::ios::binary);

std::vector<float> gt_depth(num_col*num_row, 0);
int non_inf_count = 0;

if (!gt_depth_file.is_open()) {
	std::cout << "cannot open the gt depth map" << input_depth_path << std::endl;
}
gt_depth_file.read((char*)&gt_depth[0], sizeof(float)*num_col*num_row);

for (int i = 0; i < gt_depth.size(); i++) {
	if (gt_depth[i] < float_inf)
	{
		non_inf_count++;
	}
}
gt_depth_file.close();`
Did I miss something?

**Comment by puzzlepaint** [comment]
Since from most perspectives the resolution of the DSLR camera will be higher than the resolution of the laser scanner, it is to be expected that most pixels don't have a depth value on the original DSLR resolution. So I don't think there is an issue here. Do the depth images look plausible otherwise?
