### ISSUE TITLE
error:Less than 2 images defined. when running "Step-by-step example (individual images)"

### ISSUE THREAD

**Issue by gara-9527** [ETH3D/dataset-pipeline#14]
Hi! 
 I was recently following the steps in the" Step-by-step example (individual images) "to run the code.I got some problem in step

> [external SfM tool](https://github.com/ETH3D/dataset-pipeline/tree/dc4a1069e3351bb07e26221f97ef011611af9803#external-sfm) and [external surface reconstruction tool](https://github.com/ETH3D/dataset-pipeline/tree/dc4a1069e3351bb07e26221f97ef011611af9803#external-surface-reconstruction) 

1、When i download the official SfM (Structure-from-Motion) reconstruction containing the DSLR images and the cube map images you posed in

> An SfM (Structure-from-Motion) reconstruction containing the DSLR images and the cube map images must be created using an external tool. We provide an example SfM reconstruction [here](https://www.eth3d.net/data/pipeline_examples/dslr_example_model.7z) (unzip into the same directory as the input data archives).

the TX、TY and TZ in image.txt is 

> -inf -inf inf

I estimate the scaled factor using
 `mkdir sparse_reconstruction_scaled
${PIPELINE_PATH}/SfMScaleEstimator -s sparse_reconstruction -si . -i scan_clean -o sparse_reconstruction_scaled --cube_map_face_camera_id 0` .
when i execute the command 
`${PIPELINE_PATH}/ImageRegistrator \
    --scan_alignment_path scan_clean/scan_alignment.mlp \
    --occlusion_mesh_path surface_reconstruction/surface.ply \
    --occlusion_splats_path surface_reconstruction/splats.ply \
    --multi_res_point_cloud_directory_path multi_res_point_cloud_cache \
    --image_base_path . \
    --state_path sparse_reconstruction_scaled/colmap_model \
    --output_folder_path dslr_calibration_jpg \
    --observations_cache_path observations_cache \
    --camera_ids_to_ignore 0`
the error"Less than 2 images defined"occured.（PS： The input data of this code incluing `sparse_reconstruction_scaled/colmap_model ` ）
![微信截图_20220409201221](https://user-images.githubusercontent.com/77578976/162573706-a225b30e-7472-48e0-852b-afd8ced3e1e1.png)
I found that the problem is with function `ReadColmapImages` in the file `colmap_model.cc`.
![微信截图_20220409201811](https://user-images.githubusercontent.com/77578976/162573850-38305949-b612-4eeb-8653-c6dd97b396c3.png)
The information was successfully read into the string `line`.But looks like the function ` std::istringstream`  can not recognized 

> -inf -inf inf

in `line`,so the data after the first 

> inf （Either positive or negative）

can't be read into
 `>> new_image->image_T_global.data()[4]
                 >> new_image->image_T_global.data()[5]
                >> new_image->image_T_global.data()[6]
                 >> new_image->camera_id
                 >> new_image->file_path;`respectively.
![微信截图_20220411125642](https://user-images.githubusercontent.com/77578976/162667632-ddb6defe-8413-435d-a6ac-9dcf25d0a9c7.png)

By the way,I am running this project on ubuntu 20.04.The environment is built according to the instructions in  `dockfile`.

Any suggestion about how to deal with this problem would be welcome.

![微信截图_20220411130458](https://user-images.githubusercontent.com/77578976/162668396-6a0eff08-b884-44cd-bd92-b06a89b7010a.png)
I also want to know how did you get two camera model and 
> -inf -inf inf

by using [COLMAP](http://colmap.github.io/).

I would really appreciate it if you could answer my question！

**Comment by ClementPinard** [comment]
Hello,

it seems the reader is not working properly. image_id should obviously be only an integer, so I suspect that expected and actual orders are different.

Are you able to run COLMAP on your computer ? Can you try the same thing with a SfM model created from scratch instead of the provided one ? The given model dates from 2017 so it's possible the file format has changed since.

**Comment by ClementPinard** [comment]
> You can see that only 28 images are output successfully while the provided one output 33 images,maybe there are other operations that need to be done in between?

It's not unusual to have missing images when you run COLMAP without refinement. Here is a set of advices to add more images to the model : 
https://colmap.github.io/faq.html (see [Increase number of matches](https://colmap.github.io/faq.html#increase-number-of-matches-sparse-3d-points)
I do concede that it can be somehow empirical, just test different parameters and see how it goes. The good news is that there are very few images so the trial and error should not be too painful.

> Then，error occurred. Do you have any suggestion?

It's strange that the intrinsics file was not created. See this line that is normally run when launching `cubeMapRenderer` :
https://github.com/ETH3D/dataset-pipeline/blob/master/src/exe/cube_map_renderer.cc#L146

Can you specify the options you used for this command ?

**Comment by gara-9527** [comment]
> Can you specify the options you used for this command ?

Sure,I executed the exact same command as you provided：

`${PIPELINE_PATH}/CubeMapRenderer -c scan_clean/scan1.ply -o cube_maps/scan1.ply --size 2048
${PIPELINE_PATH}/CubeMapRenderer -c scan_clean/scan2.ply -o cube_maps/scan2.ply --size 2048`.

Actually the intrinsics file has been created, but the code can't read it.

![微信截图_20220411165946](https://user-images.githubusercontent.com/77578976/162702153-09fc7d9b-b568-4677-93c5-f50de6a227a9.png)

At the same time, if I used my own created model, should the ignored camera id be modified according to my model, for example ignored_camera_id set to 2.

![微信截图_20220411155225](https://user-images.githubusercontent.com/77578976/162703390-ae9dd522-488e-4c34-9906-741fc6b173b6.png)

**Comment by ClementPinard** [comment]
It's indeed very strange. The error you get is definitely a problem of the file not being open (it still hasn't even checked if it is readable), meaning the file appears to be missing.

One shot in the dark : try to replace ` .`  by the actual absolute path in your `SfMScaleEstimator`  command.

**Comment by gara-9527** [comment]
Thanks for your kindly help! 
Problem 

> Actually the intrinsics file has been created, but the code can't read it.

is solved.I still follow the  `Step-by-step example (individual images)` to run the code.Still at [ImageRegistrator](https://github.com/ETH3D/dataset-pipeline#image-registrator) I have a different problem：
![微信截图_20220411202346](https://user-images.githubusercontent.com/77578976/162738533-dbd30316-abb5-4ca9-adb6-69554709d042.png)
(PS: It is at line 785 in the original code，I added a few lines of code for debugging. )

At the same time,I found that although the ` translation vector (TX, TY, TZ)` is numeric in my model, when reading into the stream it is still 

> inf

One line of the parameters in my model listed below:

>27 0.61476719917173828 0.37021888358273863 -0.30665750130918429 0.62526829917411819 -0.40839097764587234 -2.3500618939341655 4.9826124337543032 2 scan1.ply.left.png 

It turns to be
![微信截图_20220411205143](https://user-images.githubusercontent.com/77578976/162743161-c34f9c60-c0e8-4b01-8ed2-7bd7326417c3.png)
in `line`.
![微信截图_20220411205012](https://user-images.githubusercontent.com/77578976/162742893-58ab76de-8dde-43cc-b99b-57086a5506da.png)
Maybe there is something wrong with the previous code? If this problem is not solved, problem `Less than 2 images defined`still remains.

**Comment by gara-9527** [comment]
I have set the global factor to 1 as you suggested https://github.com/ETH3D/dataset-pipeline/pull/15.

Running a test with my own model using the docker image 

> A Dockerfile is given to build everything from scratch in ubuntu 20.04.

Still in [ImageRegistrator](https://github.com/ETH3D/dataset-pipeline#image-registrator),error
![微信截图_20220413103237](https://user-images.githubusercontent.com/77578976/163106000-8cbe067a-7887-4b25-9556-105ec3a666a3.png)
 occures at https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/io/colmap_model.cc#L784-L786
When using the model provided by 

> We provide an example SfM reconstruction [here](https://www.eth3d.net/data/pipeline_examples/dslr_example_model.7z) (unzip into the same directory as the input data archives).

,this problem wouldn't happen.（But I still don't know if the code will work as it's still iterating）
This problem arises very strangely because my model is also generated with [COLMAP](http://colmap.github.io/).What is the key to making `a`equal to `b`？
My models are listed below：
[cameras.txt](https://github.com/ETH3D/dataset-pipeline/files/8478466/cameras.txt)
[images.txt](https://github.com/ETH3D/dataset-pipeline/files/8478467/images.txt)
[points3D.txt](https://github.com/ETH3D/dataset-pipeline/files/8478480/points3D.txt)

**Comment by ClementPinard** [comment]
(Sorry the issue got automatically fixed, wasn't intentional, I reopened it)

**Comment by ClementPinard** [comment]
Glad to see we are making progress ! :)

See Colmap's thin prism fisheye definition here :
https://github.com/colmap/colmap/blob/master/src/base/camera_models.h#L349

As you can see, it's 12 parameters. ETH3D checks that the camera model described in the cameras.txt matches the number of floats in the line, hence the given assertion. For some reason, ETH3D reads 13 parameters which then fails because because it's not 12.

See here for how the camera line is read : https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/io/colmap_model.cc#L53

It seems to me the cameras.txt you provided is fine, so something goes wrong during the reading.

I will do tests on my own, might be worth it trying to log what are these 13 parameters to understand where things went wrong.

**Comment by kakghiroshi** [comment]
Thanks for your work！:thumbsup:
I have found the cause of the problem.I firstly using  [COLMAP-3.7-windows-no-cuda.zip](https://github.com/colmap/colmap/releases/download/3.7/COLMAP-3.7-windows-no-cuda.zip) in windows,I guess Windows have different output format compare with Linux(build from source code) version.Specifically,the escape characters they use are different, so the model generated by windows is incorrectly recognized in linux,like:
![微信截图_20220414181801阿斯顿](https://user-images.githubusercontent.com/77578976/163529037-583605b6-36ad-46f4-b008-2e0a6d1044da.png)
The actual size of the parameter line is 55,The code does recognize that the string size is 56.I guess the extra string contains nothing, so it is 0.Using the model created by Linux version COLMAP,the problem is fixed:
![微信截图_20220415141524](https://user-images.githubusercontent.com/77578976/163529441-3bef6723-bc52-4313-be24-dd9b4d7ab322.png)
Stil running `Step-by-step example`   :triumph: ,still in [ImageRegistrator](https://github.com/ETH3D/dataset-pipeline#image-registrator) using code 

> ${PIPELINE_PATH}/ImageRegistrator \
    --scan_alignment_path scan_clean/scan_alignment.mlp \
    --occlusion_mesh_path surface_reconstruction/surface.ply \
    --occlusion_splats_path surface_reconstruction/splats.ply \
    --multi_res_point_cloud_directory_path multi_res_point_cloud_cache \
    --image_base_path . \
    --state_path sparse_reconstruction_scaled/colmap_model \
    --output_folder_path dslr_calibration_jpg \
    --observations_cache_path observations_cache \
    --camera_ids_to_ignore 2

Problem 
![微信截图_20220415143946](https://user-images.githubusercontent.com/77578976/163532005-5f26d6a6-198d-462d-a277-0c63bd77127e.png)

occurred.I try to replace `   --image_base_path . \` with `   --image_base_path dslr_images \`,it doesn't work.

![微信截图_20220415144110](https://user-images.githubusercontent.com/77578976/163532028-2be47650-2441-4e6b-b5fc-660b38bc35d6.png)
The code I added:
![微信截图_20220415143730](https://user-images.githubusercontent.com/77578976/163532163-aab58ec5-e44b-4f25-91db-d3496df0048f.png)
Any suggestion would be needed.Thanks again!

**Comment by kakghiroshi** [comment]
Hi！
Recently I am trying to apply your code to my project.However, the difference is that the point cloud we obtain does not contain the property of color.The point cloud is densified by slam and stitched together.In the step [CubeMapRenderer](https://github.com/ETH3D/dataset-pipeline#cube-map-rendering) ,cube map face images are rendered from the laser scans with color.I wonder if the property of intensity can be used to render cube map face images instead of color(for our point cloud don't have the property of color) in step [CubeMapRenderer](https://github.com/ETH3D/dataset-pipeline#cube-map-rendering).
Of course, the code needs to be modified to achieve intensity image rendering.
Can you give me some advice?Thanks! :blush:

**Comment by ClementPinard** [comment]
Thanks for your insight ! Indeed I forgot about the line ending confusion between linux and windows... good to know, I'll try to update the README to wanr people about this issue !

For your problem, this is the main limitation for this work, it needs colored point clouds, which is not easy to get, and the scanner that are able to do that are very slow. You can't user the point cloud from a handheld device like the Zeb Horizon.

Shameless plug, but you might want to have a look at my own project that uses colorless point clouds : https://github.com/ClementPinard/depth-dataset-builder (there's an ArXiV article that comes with it)

It uses the functions from this repo as well, but the localisation of frames with respect to the lidar point cloud is mostly done with ICP, and not by trying to incorporate the Lidar rendering in the COLMAP reconstruction

If you look at the original publication (https://www.eth3d.net/data/schoeps2017cvpr.pdf , Figure 4), they did try ICP and got worse results, but it's not so bad given that it allows you to use colorless pointcloud. They did not implement it in this repo because it was probably a very manuel alignment which could not be converted into a usable tool without some additional work.

**Comment by ClementPinard** [comment]
For your problem with ImageRegistrator, it depends what the filepaht is in the `images.txt`  of your colmap model. In the provided one, the path is in the format `dslr_images/DSC_0285.JPG`  It means that image base path must be the path to the parent of the `dslr_images` folder.

In a sense, your second screenshot is right with that assumption. What is weird is your first screenshot where the `file_path`  (which should be literally the path written in the colmap file) is said to be `./DSC_0275.JPG`  It's weird that there is the `.` in this path.

Did you modify the `images.txt` file manually ? If not, is the file different from the provided one ?

**Comment by kakghiroshi** [comment]
This project may indeed be helpful in our work! Thank you for your dedication.I will add this project in my to-do list.

> For your problem with ImageRegistrator, it depends what the filepaht is in the images.txt of your colmap model. In the provided one, the path is in the format dslr_images/DSC_0285.JPG It means that image base path must be the path to the parent of the dslr_images folder.

I do check my filepath in the images.txt and solve this problem,thanks again!
For our camera's low resolution(1024*768 ,probably.),running [Step-by-step example (camera rig images)](https://github.com/ETH3D/dataset-pipeline#:~:text=write_occlusion_depth%201%20%5C%0A%20%20%20%20%2D%2Dwrite_scan_renderings%201-,Step%2Dby%2Dstep%20example%20(camera%20rig%20images),-This%20example%20shows)maybe meaningful.The code works perfect.
Given that I have successfully run both examples, I try to observe their alignment in [ImageRegistrator](https://github.com/ETH3D/dataset-pipeline#image-registrator) .
Here comes several questions:

1: In [Step-by-step example (individual images)](https://github.com/ETH3D/dataset-pipeline#:~:text=in%20ubuntu%2020.04.-,Step%2Dby%2Dstep%20example%20(individual%20images),-For%20this%20example),the resulting depth map I get has many holes.
![微信图片_20220420195743](https://user-images.githubusercontent.com/77578976/164225949-ccd36501-63c1-4ec9-a64c-21aea5134f53.jpg)
![微信图片_20220420195739](https://user-images.githubusercontent.com/77578976/164225827-5af923a0-a20e-4712-988f-3807ef34c388.jpg)
Compare with your posted depth map:
![image](https://user-images.githubusercontent.com/77578976/164226177-b96c4d3a-fe26-4ad9-8d62-db52a9160121.png)(capture from README.md)
Do you know what cause this?

2: There are rarely scan reprojection points on the left wall(annotated by white box),but opposite on the wall facing(annotated by yellow box) and on the left(annotated by red box,weird for different density in the same wall).
![b9c0da3f4d5cdeaa2b6cf2a7eed7d32](https://user-images.githubusercontent.com/77578976/164228463-5a25ec15-25bf-4c30-bec5-6e6c978b189a.jpg)
what makes this difference?

3:In [Step-by-step example (camera rig images)](https://github.com/ETH3D/dataset-pipeline#:~:text=write_occlusion_depth%201%20%5C%0A%20%20%20%20%2D%2Dwrite_scan_renderings%201-,Step%2Dby%2Dstep%20example%20(camera%20rig%20images),-This%20example%20shows),depth map only covers the area in the center of the image, the edge of the image does not contain the depth information.Is it normal?
![微信截图_20220420202440](https://user-images.githubusercontent.com/77578976/164230038-b78d6bf1-d061-421c-8841-57b7407659b3.png)
Looking forward to your reply! :grin:

**Comment by ClementPinard** [comment]
Most likely, the occlusion model is in front of the actual model. The points are thus deemed occluded and are not shown. A first solution would to try other options to generate the occlusion mesh so that it has a better quality.

You might also want to have a look at the global parameters : https://github.com/ETH3D/dataset-pipeline/blob/master/src/opt/parameters.h

More specifically, in this case, the problem is that the `occlusion_depth_threshold` is too low, and thus too strict. If a point has a depth greater than occlusion depth + threshold, then it's not visible. Raise the threshold and more points will show.

For the second use case, it's indeed pretty weird. Looks like a problem with the camera model. Somehow the polygons around the center of the image did not render, making the occlusion depth there at 0, which means everything is occluded. You can check that intuition by looking at the "occlusion depth map" in the select mode.

If this is true, this might be a bug that we have to look into. I know that some extreme camera models + parameters can give up rendering at the edge of the screen, but I didn't know it occurred for the  low-res cameras !
