### ISSUE TITLE
Question about the radius_cutoff threshold in camera with distortion parameters

### ISSUE THREAD

**Issue by liu115** [ETH3D/dataset-pipeline#16]
In both opengl rendering and the pose optimization, when it comes to the camera with radial distortion, a radius_cutoff threshold is applied. I'm interested and curious what is the idea behind this term? 

For example:
https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/opengl/renderer.cc#L486
https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl_fisheye.h#L71

I tried to remove the threshold during rendering from a mesh and got wrong depth map like this. Therefore, I assuming that the radial distortion could project the things that aren't in the camera view frustum, such as vertices in the back of the camera, so we need some threshold constraining the field-of-view during rendering.
![image](https://user-images.githubusercontent.com/8998128/206861103-d1f6adf0-82da-4adf-bb22-173dd3ec4e95.png)

Also, I notice that the threshold is computed from the data instead of a pre-defined value. Could you roughly explain the idea how it was computed? 
https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl.h#L410

It's greatly appreciated if someone can point me some directions or resources for the radius cutoff.
Thanks for sharing the awesome code base.

**Comment by ClementPinard** [comment]
Hi,

Your assumptions are right, it's about preventing pixel out of the normal frustum to be projected back to the image plane.

The way it works is that the distortions are compressing pixels with distance from the center (in the same way a fisheye does). In other words, the distortion function f(r) has a decreasing derivative. When using polynomial distorsion, it can happen that at some point, the derivative becomes negative, which means the porjected pixel is getting backward, getting projected onto the already projected ones.

This is a collateral we want to avoid. the radius cutoff is thus the radius at which the derivative is 0, and above which we don't project pixels anymore.

**Comment by liu115** [comment]
Hi @ClementPinard,

Thanks a lot for the explanation. It really helps!

Based on what you said, finding the radius cutoff is basically a root finding process right? Could you roughly explain how it's done in the implementation?

I found it hard to understand looking at the code. For example, in the code, it's fitting some sample points. However, there's no depth info for those points. How can I know where they are projected at the end?

**Comment by puzzlepaint** [comment]
> Based on what you said, finding the radius cutoff is basically a root finding process right? Could you roughly explain how it's done in the implementation?

This could be implemented that way, but the implementation in `InitCutoff()` actually works differently. If I remember correctly, it iterates over all pixels that are at the camera image edges (since those supposedly have the largest radius values), and tries to compute the radius values that would be used in the point projections that would have these edge pixels as results. Then it tries to set the radius cutoff such that these image edge pixels can still be projected, but everything with larger radius is rejected.

The depth info is not needed at this point, since only the inner parts of the projection "pipeline" are considered here. The complete pipeline (from local 3D point to pixel) would consist of these steps:

https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl.h#L115

The operations to compute the radius cutoff start with pixels in the image (the last step in the above pipeline), compute the corresponding distorted image coordinates and try to find normalized image coordinates that map to the distorted image coordinates, but they never deal with the leftmost part that (from right to left) would un-project normalized image coordinates to local 3D points. Thus, depth information is never needed.

**Comment by ClementPinard** [comment]
> This could be implemented that way, but the implementation in InitCutoff() actually works differently

It's actually implemented that way for some simple models, like simple radial :
https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_simple_radial.cc#L55

But yeah, the general usecase is to get the radius of points that would be projected to the image edge. This is generally a smaller value than the actual radius cutoff so we avoid the problem you depicted in your first message, because this operation is made with the assumption that the actual radius cutoff is larger than the radius of projected points in the edge of the image, i.e. the overlap is happening outside of the image. This is a reasonable assumption to make since the expected output comes from COLMAP which gives reasonable distortion parameters.

More generally, the radius_cutoff is done the simplest possible way for a given model. For radial models, only compute the undistorted radius of the furthest corner from the optical center, for more general models with potential tangential distortion, compute the radius for all points in the image perimeter, no exception, you are never too sure what the distorsions are capable of with some expressions ! 😂

https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl_radial.h#L142

https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl.h#L410

**Comment by liu115** [comment]
Hi, thanks @puzzlepaint  and @ClementPinard  for the explanation. I learned a lot from it. May I asked the last minor question that how the cutoff of simple radial is computed? 

For simple radial camera model, isn't the distortion polynomial $1+k_1 r^2$, which will never be negative. From the equation you showed above, I'm guessing it's the derivative of $r+k_1r^3=0$. Where is the additional $r$?

Thanks again for the help! I will close the issue after this.

**Comment by ClementPinard** [comment]
it can be negative in the case of a negative k1, which is often the case when trying to recreate the fisheye effect.

The additional r comes from the fact that distorsion is writtent as f(r) * r. If f < 1, image is compressed, if d/dr (f(r)*r) < 0, image is overlapping on itslef, which we don't want.

See how distorsion is applied here for radial cameras : https://github.com/ETH3D/dataset-pipeline/blob/dc4a1069e3351bb07e26221f97ef011611af9803/src/camera/camera_base_impl_radial.h#L54

As such, for simple radial, we know right away that if k1 < 0, the overlapping will occur at r such that r + k1r^3 = 0, as you mentionned.
