### ISSUE TITLE
Code replication on Camera models

### ISSUE THREAD

**Issue by ClementPinard** [ETH3D/dataset-pipeline#4]
Hi,

As discussed earlier, I tried to add some camera models in your codebase. More specifically, I'm working to add `SIMPLE_PINHOLE`, `RADIAL` and `SIMPLE_RADIAL` to the available cameras

It can be noted that these are theoretically simpler sub-models of `PINHOLE` for `SIMPLE_PINHOLE` and `POLYNOMIAL` for `RADIAL` `SIMPLE_RADIAL`

While trying to extend the code, I came across two concerns : 
 - There's a lot of code replication, and i didn't manage to not add even more with these new models. It's a pity, because many functions are actually only calling more specific functions and perform the same thing everywhere, e.g. InitCutoff ([here](https://github.com/ETH3D/dataset-pipeline/blob/master/src/camera/camera_polynomial_tangential.cc#L95) and [here](https://github.com/ETH3D/dataset-pipeline/blob/master/src/camera/camera_benchmark.cc#L105) or [InitializeUnprojectionLookup](https://github.com/ETH3D/dataset-pipeline/blob/master/src/camera/camera_polynomial_tangential.cc#L58) , sometimes called simply [Init](https://github.com/ETH3D/dataset-pipeline/blob/master/src/camera/camera_polynomial.cc#L74). The main reason I could not solve this replication is the fact that function are heavily templated, and inheritance, polymorphism and overriding seem to not be possible with templated function. However, I could see that the templates were mostly about Eigen vector type, and I couldn't see were it was called with something else than float vectors. Is there a reason for templating then ? Was it serving another purpose with not publicated code ? It is very tempting to make everything a regular float function to dramatically reduce the amount of code, but coming from python, I'm a bit lousy on c++ and might not see a problem that this will cause.
 - Some problems remain with polynomail models, the camera test program will fail if we test it on specific distorsion codes. After checking it up, this is mostly due to the Undistort function with a Gauss-Newton that fails to converge when the first distorsion parameter is negative (and thus the image look's like a crop of a fisheye). Also it seems that the "radius_cutoff" used by polynomial_tengantial should also be used by the polynomial model (and therefore radial and simple radial). However, I could see that adding the InitCutoff routine to the Polynomial model made the test of camera fail, because some points were outside that radius cutoff. I might investigate it further, but this is suspicious, as the cutoff radius is simply the max radius of undistorted points of the frame borders, it might be due to the different Undistortion function called in this routing, `UndistortFromInside`.
- Lastly, I am a bit curious about the difference between "ProjectionToNormalizedTextureCoordinatesDerivative" and "ProjectionToImageCoordinatesDerivative" every camera model seem to have. It seems that these functions are identical, and "ProjectionToNormalizedTextureCoordinatesDerivative" is only called for tests. Is it here again parts of some unpublished code ?

Thanks for your help !

**Comment by puzzlepaint** [comment]
* The templates in the style of `template <typename Derived> [...] const Eigen::MatrixBase<Derived>& something` are not only for being able to use float or double. They can sometimes also improve performance, since Eigen may potentially be able to optimize its calculations more then. In contrast, if one passed for example an `Eigen::Vector3f` to a function instead of the template, this would force to explicitly calculate the elements of this vector object, potentially leaving less room for optimization.
  However, I would be pretty certain that with some work, the code replication could still be reduced. For example, what could be done is to make certain similar camera model classes derive from a templated class `template <typename Derived> class SomeClassOfCameras : public CameraBase { ... };`. This would be used as follows: `class SpecificCameraClass : public SomeClassOfCameras<SpecificCameraClass> { ... };`. This way, the more generic `SomeClassOfCameras` can implement generic algorithms that apply to this class of cameras, such as for example computing the undistortion lookup, and within these algorithms it can call the specific undistortion functions that are only implemented in the derived class.

* Potentially, it might help to extend the Gauss-Newton algorithm to Levenberg-Marquardt if the former fails to converge. In general, it might very well be that other camera models than the one which was used for the benchmark in the end don't work as well.

* The difference is that the `NormalizedTextureCoordinates` variant uses the normalized focal length (`nfx()` and `nfy()`), while the `ImageCoordinates` uses the standard focal lengths (`fx()` and `fy()`). The idea of the normalized texture coordinates is simply that the image area is always in the domain (0, 0) - (1, 1) instead of (0, 0) - (width, height), which may be more suitable for certain uses of the camera models, such as if the computed pixel coordinates are used as texture lookups in CUDA. However, it is really just a different scaling of the output (doing this via scaling the focal length may make it a tiny bit faster compared to first using the standard focal length and then scaling the result again). If it is not used anywhere, it is safe to delete to reduce the code complexity.
